engines:
  tslint:
    enabled: true
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - typescript
ratings:
  paths:
  - src/**
exclude_paths:
- "src/index.test.js"
